server.port=8090
spring.application.name=GATEWAY

# Import config from Spring Cloud Config Server
spring.config.import=optional:configserver:http://localhost:8883

# Eureka config
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}

# Logs
management.endpoints.web.exposure.include=health,info,gateway
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Dynamic microservice discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# JWT Keycloak Resource Server (realm web4all)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/web4all
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/web4all/protocol/openid-connect/certs

# Routes statiques vers les services NestJS (non enregistrés dans Eureka)
spring.cloud.gateway.server.webflux.routes[0].id=crawler-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:3002
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/crawler/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[1].id=report-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:3001
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/report/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[2].id=audit-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:3005
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/audit/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=2
